WARNING 2025-05-03 02:30:32,422 log Bad Request: /api/active-modules/
WARNING 2025-05-03 02:31:48,873 log Bad Request: /api/validate-values/
WARNING 2025-05-03 02:31:58,709 log Bad Request: /api/validate-values/
WARNING 2025-05-03 02:32:08,707 log Bad Request: /api/validate-values/
WARNING 2025-05-03 02:33:10,741 log Bad Request: /api/validate-values/
ERROR 2025-05-03 02:34:51,837 log Internal Server Error: /api/recalculate-values/
Traceback (most recent call last):
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/core/views.py", line 62, in recalculate_values
    DataCenterValueService.recalculate_all_values()
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/core/services.py", line 154, in recalculate_all_values
    spec = DataCenterSpecs.objects.get(unit=unit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivamarinova/hack-upc/hackupc/backend-api/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 636, in get
    raise self.model.MultipleObjectsReturned(
core.models.DataCenterSpecs.MultipleObjectsReturned: get() returned more than one DataCenterSpecs -- it returned 3!
